.SH NAME
.PP
md-lsp - markdown language server
.SH SYNOPSIS
.PP
md-lsp [\fIOPTIONS\fP]
.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP
.RS 8
Show help message
.RE
.PP
\fB-v\fP, \fB--version\fP
.RS 8
Show the version
.RE
.SH TEST
.PP
Inline code looks like \fCthis\fP.
A code block looks like this the following:
.SS Code Block
.EX
man mdman
.EE
.SS Lists

.RS
.IP \(bu 2
\fBone\fP
.RS
.IP \(bu 2
sublist1
.IP \(bu 2
sublist2
.RS
.IP \(bu 2
more nested

.RE

.RE
.IP \(bu 2
two
.IP \(bu 2
three

.RE