.SH NAME
.PP
md-lsp - markdown language server
.SH SYNOPSIS
.PP
md-lsp [\fIOPTIONS\fP]
.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP
.RS 8
Show help message
.RE
.PP
\fB-v\fP, \fB--version\fP
.RS 8
Show the version
.RE
.SH TEST
.PP
Inline code looks like \fCthis\fP.
A code block looks like this the following:
.EX
man mdman
.EE
.PP
| tets | table |
|------|-------|
|a     |b      |
